spring:
  application:
    name: Loop

  data:
    mongodb:
      uri: ${MONGODB_URI:mongodb://localhost:27017/loop_db}

server:
  port: ${SERVER_PORT:8080}

custom:
  client_prod: ${CLIENT:http://localhost:4173/}
  client_dev: ${CLIENT:http://localhost:5173/}
